### ISSUE TITLE
It still works?

### ISSUE THREAD

**Issue by F4bbi** [peinguin/ThroneRushBot#2]
I have tried the command "go build *.go ./config" but the .exe doesn't do anything, so i was wondering if there was a guide on how this works.

**Comment by peinguin** [comment]
It was working... 8 years ago.
It works in a command line interface.

But has a web interface too. The endpoint is `/bot`
https://github.com/peinguin/ThroneRushBot/blob/master/bot/bot.go#L150

**Comment by peinguin** [comment]
One more think. You have to fill keys by yourself.
https://github.com/peinguin/ThroneRushBot/blob/master/config.go.example

Take it from the browser http request.
